### PR TITLE
Add bundling of ui5

### PR DESCRIPTION
**Pull request by rajanasrallah**

### CODE REVIEW

**Comment by gadisn** [comment]
What's is this repo being used for? Do we really need to copy the ui5 bundling her?

**Comment by idogoren** [comment]
This logic should not be introduced here but in the WebIDE template project. (MTA template)

**Comment by idogoren** [comment]
ok

**Comment by bd82** [comment]
it looks like we are getting more and more variants of the "example extension"
maybe we should prioritize the finishing touches on the yeoman generator so
we could avoid all these duplications.

**Pull request merged**
